# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
julia:
  - 1.0
notifications:
email: false

after_success:
- julia -e 'cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
